### ISSUE TITLE
Badger doesn't appear to work on new tabs.

### ISSUE THREAD

**Issue by duncanparkes** [EFForg/privacybadger#1078]
If I open a site (for example, www.theregister.co.uk) and then open one of the links there using 'open in new tab', Privacy Badger always reports nothing needed blocking and allows all the trackers on the new tab. Opening in a new window results in normal blocking behaviour.

Firefox version 50.1.0 (Ubuntu)
Badger version 2016.12.8.1

**Comment by cooperq** [comment]
This should be fixed as of version 2016.12.15.1, please re-open if it is not.

**Comment by aereaux** [comment]
This issue does not appear to be fixed as of v. 2016.12.15.1, even after restarting my browser.

**Comment by hungerburg** [comment]
Issue is here, latest version installed; also on Ubuntu, 16.04; not the creator, I can't reopen?

**Comment by duncanparkes** [comment]
This is still a problem for me on 2016.12.15.1, Firefox 50.1.0, Ubuntu.

**Comment by duncanparkes** [comment]
As far as I can see I can't reopen the issue either, and I am the creator...

**Comment by duncanparkes** [comment]
It looks like we need @cooperq to reopen it.

**Comment by cooperq** [comment]
I think that this is the same issue as #1101 do you agree? If so I will keep this issue closed in favor of that one. If not I will re-open.

**Comment by duncanparkes** [comment]
I think these are two independent bugs.

My problem has nothing to do with having visited a URL before. If I open a URL in a new tab, PB doesn't see any trackers. If I open the same URL again in a new tab, the same thing happens. If I copy the URL, open a new tab, paste the URL in the location box and press enter, then PB works as expected.

**Comment by hungerburg** [comment]
On the visible surface, these are different issues, I side with @duncanparkes - I see both, so depending on the inner workings of FF and PB though, the fix for the other might cure this one too - very likely only a fix for the other issue will show!
PS: It started when FF upped to 50 something from the immediately preceding release, "ps" shows just one firefox process; the only other add-on active here is self-destructing cookies.
