### ISSUE TITLE
cannot 'Edit in Browser' in Office 365 (SharePoint)

### ISSUE THREAD

**Issue by marignymohican** [EFForg/privacybadger#1287]
With Privacy Badger installed, choosing to edit a Word document in browser causes the page to never load with the editing interface. Even if you've selected to 'Disable Privacy Badger on this site'.

This is happening to me in Firefox 52 on Mac OS 10.12.3. Reverting to Firefox 51, this problem went away. In Google Chrome (57), there is no problem even with Privacy Badger enabled.

**Comment by ghostwords** [comment]
What version of Privacy Badger do you have? You can find out by going to `about:addons`, clicking on "Extensions", and then the "More" link next to Privacy Badger's listing.

**Comment by marignymohican** [comment]
i'm using Privacy Badger 2017.3.28

**Comment by ghostwords** [comment]
Could you try opening one of these documents using the browser/addon setup that causes it to break, open the Firefox developer tools console (by pressing either F12 or Cmd-Shift-I), and then either copy/paste or share a screenshot of the messages there? I'm including an example screenshot below.

Also, are any of these documents public for us to look at (or, would you be able to share any of them with me)?

![screenshot from 2017-03-30 17 03 27](https://cloud.githubusercontent.com/assets/794578/24526131/f6b12722-156a-11e7-9a65-0b6500cb4b4d.png)

**Comment by marignymohican** [comment]
here is everything from the console.
![privacybadger-sharepoint](https://cloud.githubusercontent.com/assets/6052222/24528797/d2476f7e-156d-11e7-8db0-fb294fe68d0d.png)

this link should allow editing for 24 hours:
https://advancelocal.sharepoint.com/sites/NOLA/digital_ops/_layouts/15/WopiFrame.aspx?docid=1cf76cffbaf2a43deae0c72570bf2c392&authkey=ATgsghHSfjFMtqxWgfWy_rs&action=view

**Comment by ghostwords** [comment]
I don't see anything relevant in the console, which makes me think the page gets broken because Badger ends up blocking too much. Although I am confused by "Even if you've selected to 'Disable Privacy Badger on this site'" ... Selecting that option and reloading the page (if it hasn't reloaded already) should fix it.

What does Badger report as found and blocked on the site? Here is what I see:
![screenshot from 2017-03-30 18 51 09](https://cloud.githubusercontent.com/assets/794578/24529487/f6ce87a4-1579-11e7-957f-950cefc30c70.png)

**Comment by marignymohican** [comment]
i'm seeing things a bit different it looks like. with the Badger enabled, i only get a white screen when only viewing the document:

![privacybadger-whatsblocked](https://cloud.githubusercontent.com/assets/6052222/24529821/9d420cca-1573-11e7-9e0f-a4e02089f649.png)


then, disabling it on the page, i must manually refresh but i _can_ then view the document, however, i still cannot use the Edit in Browser option as the interface never loads:

![privacybadger-whatsblocked-disabled](https://cloud.githubusercontent.com/assets/6052222/24529905/20eec950-1574-11e7-9b29-c5418290c159.png)

**Comment by ghostwords** [comment]
What if you instead of disabling on the site, you tell Badger to unblock `word-view.officeapps.live.com`?

I can reproduce that blocking `word-view.officeapps.live.com` breaks the page, but disabling Badger for the site fixes the page for me on Firefox 52 ...

**Comment by ghostwords** [comment]
I think the fix for us would be to add `sharepoint.com` to the [list of Microsoft domains](https://github.com/EFForg/privacybadger/blob/8266dbb8e1f5b0ff986553eba7476904148d64de/src/js/multiDomainFirstParties.js#L45-L48), so that Badger stops learning to block that `live.com` domain there.

Not yet sure what's going on with site disabling though.

**Comment by ghostwords** [comment]
Could you share your snitch map for `live.com`? This will tell us where PB saw this domain perform suspected tracking.

To get the snitch map in Firefox now (we'd like to make this simple in the future):
1. Visit `about:debugging`
2. Enable add-on debugging
3. Click Debug on Privacy Badger's row
4. Click OK
5. Paste the following into the >> prompt on the bottom of the window that should have come up: `badger.storage.snitch_map.getItem("live.com")`.

(In my case the result is `Array [ "sharepoint.com" ]`)
