### ISSUE TITLE
Translations for replaced Facebook button

### ISSUE THREAD

**Issue by jony0008** [EFForg/privacybadger#1439]
When hovering the replaced Like button the text "PrivacyBadger has replaced this FacebookLike button" appears. Shouldn't "PrivacyBadger" and "FacebookLike" be "Privacy Badger" and "Facebook Like button"? Could these strings also be translated in Transifex?

![privacybadger](https://user-images.githubusercontent.com/23194385/27260124-26ab3538-5424-11e7-856e-663fc471d9e0.png)

**Comment by ghostwords** [comment]
To fix, we should move ["Privacy Badger has replaced ..."](https://github.com/EFForg/privacybadger/blob/6ef587087c2d0a13853a914cb6449f7d1d1125a1/src/js/contentscripts/socialwidgets.js#L110-L111) to a locale message. Since the `socialwidgets.js` content script doesn't have direct access to translations, we would send the message to it from the background page, maybe in response to "checkSocialWidgetReplacementEnabled".

We should also be able to tweak a few of the widget names by renaming their keys in `socialwidgets.json`; "Facebook Like" instead of "FacebookLike", for example.

**Comment by cowlicks** [comment]
I coincidentally fix this typo in #1432.

**Comment by alexristich** [comment]
Should be fixed as #1432 has now been merged.

**Comment by ghostwords** [comment]
This issue is also about making "Privacy Badger has replaced XXX" translatable. See [my above comment](https://github.com/EFForg/privacybadger/issues/1439#issuecomment-309494042).

**Comment by alexristich** [comment]
Sorry, you're right! I missed that part for some reason. Updated the title of the issue to make it a bit clearer.

**Comment by jony0008** [comment]
In the latest release (2017.7.24), "FacebookLike" has not been changed.

**Comment by ghostwords** [comment]
Correct, that's not fixed yet, only the "PrivacyBadger" bit was tweaked to say "Privacy Badger" in the currently hard-coded, English-only "Privacy Badger has replaced this ..." message.
