### ISSUE TITLE
is blocked This page has been blocked by Chrome ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by ioqq** [EFForg/privacybadger#3011]
In Chrome version 129.0.6665.0, when selecting text with the mouse and using Google Search, the page is often blocked by pkehgijcmpdhfbdbbnkijodmdjhbjlgp. Is this a Chrome issue?
![erro](https://github.com/user-attachments/assets/d27a94b4-a98f-4dba-9475-173f21939f6e)
chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/data/web_accessible_resources/redirect.html?url=

**Comment by ghostwords** [comment]
Hello! This sounds like the same issue as #2998, but it should be fixed in Chrome at this point.

**Comment by ghostwords** [comment]
As a temporary workaround, open Privacy Badger's options page, select the Disabled Sites tab, and add `www.google.com` to the list of sites where Privacy Badger is disabled.

**Comment by ghostwords** [comment]
When this happens, is it always in an Incognito window, or does it happen in regular browsing windows too?

**Comment by ioqq** [comment]
> 当发生这种情况时，是否总是在隐身窗口中发生，还是也会在常规浏览窗口中发生？
Hello, I am using the Canary version. The incognito window does not appear, only the regular window does, even though I have disabled [www.google.com](http://www.google.com/) in the settings. This issue persists, and I am using the daily build version 129.0.6667.0 (official build) Canary (64-bit) (cohort: Clang-64). The issue described in https://github.com/EFForg/privacybadger/issues/2998 occurred in July; shouldn't it be fixed in the Canary version? Chrome 127 does not have this issue.
您好，我使用的是canary版本，使用无痕窗口不会出现，只出现在常规窗口，但是我已经在设置中禁用了www.google.com，依然会出现这个问题，我使用的是每日构建版本129.0.6667.0 (正式版本) canary （64 位） (cohort: Clang-64) ，https://github.com/EFForg/privacybadger/issues/2998发生在7月份，canary版本应该修复了吧，chrome127不会出现这个问题
![d1](https://github.com/user-attachments/assets/18d4d83e-84de-4d77-9a36-461696b1c989)
![d3](https://github.com/user-attachments/assets/4a1c9d55-402d-4703-888d-29bb34a1725d)
![d2](https://github.com/user-attachments/assets/fbeb5728-d7cf-4406-a4c0-3f41f09f03e8)

**Comment by ioqq** [comment]
Hello, I am using the Canary version. The incognito window does not appear, only the regular window does, even though I have disabled [www.google.com](http://www.google.com/) in the settings. This issue persists, and I am using the daily build version 129.0.6667.0 (official build) Canary (64-bit) (cohort: Clang-64). The issue described in https://github.com/EFForg/privacybadger/issues/2998 occurred in July; shouldn't it be fixed in the Canary version? Chrome 127 does not have this issue.
> 当发生这种情况时，是否总是在隐身窗口中发生，还是也会在常规浏览窗口中发生？
您好，我使用的是canary版本，使用无痕窗口不会出现，只出现在常规窗口，但是我已经在设置中禁用了www.google.com，依然会出现这个问题，我使用的是每日构建版本129.0.6667.0 (正式版本) canary （64 位） (cohort: Clang-64) ，https://github.com/EFForg/privacybadger/issues/2998发生在7月份，canary版本应该修复了吧，chrome127不会出现这个问题
![d2](https://github.com/user-attachments/assets/f9b40e34-6c19-4188-bc34-eb1b598c4e73)
![d3](https://github.com/user-attachments/assets/135ee366-39da-43c5-8f3c-02adcb51f07a)
![d1](https://github.com/user-attachments/assets/aac4b99d-7923-43fb-94b8-507a81d1afb3)
![d2](https://github.com/user-attachments/assets/b6277ae6-0b8d-4a56-8622-d4a0e2da3954)

**Comment by ioqq** [comment]
> 当发生这种情况时，是否总是在隐身窗口中发生，还是在经常窗口中发生？

Hello, I am using the Canary version. The incognito window does not appear, only the regular window does, even though I have disabled [www.google.com](http://www.google.com/) in the settings. This issue persists, and I am using the daily build version 129.0.6667.0 (official build) Canary (64-bit) (cohort: Clang-64). The issue described in https://github.com/EFForg/privacybadger/issues/2998 occurred in July; shouldn't it be fixed in the Canary version? Chrome 127 does not have this issue.
您好，我使用的是canary版本，使用无痕窗口不会出现，只出现在常规窗口，但是我已经在设置中禁用了www.google.com，依然会出现这个问题，我使用的是每日构建版本129.0.6667.0 (正式版本) canary （64 位） (cohort: Clang-64) ，https://github.com/EFForg/privacybadger/issues/2998发生在7月份，canary版本应该修复了吧，chrome127不会出现这个问题 
![d3](https://github.com/user-attachments/assets/1eb0e407-e771-4b2f-a3c4-a2d947f12aa9)
![d1](https://github.com/user-attachments/assets/46dc0f00-de27-424b-ba80-9b20077fc7c8)
![d2](https://github.com/user-attachments/assets/5a467b54-dda3-4a7f-9d7f-2ccd407be650)

**Comment by ghostwords** [comment]
Ah, try adding your localized Google search domain (`www.google.cn`?) to the list of sites where Privacy Badger is disabled instead.
